apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hvrf9okkz-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hvrf9okkz-java-springboot-gitops